### ISSUE TITLE
use t2 topology

### ISSUE THREAD

**Issue by Ballen7** [ShawnHymel/introduction-to-zephyr#1]
Obvservation i had.... The way you copy the modified `west.yml` leads me to believe you are not aware of [t2 workspace topologies](https://docs.zephyrproject.org/latest/develop/west/workspaces.html#t2-star-topology-application-is-the-manifest-repository). I think for this use case it would make sense to use a t2 topology and use the [name-allowlist](https://github.com/zephyrproject-rtos/example-application/blob/3af081a643b2362e57fcde474b802b015d73f58f/west.yml#L4-L22) to only pull in things you want.

cheers

**Comment by ShawnHymel** [comment]
Thanks for the suggestion. I spent a few days tinkering with the T2 and T3 topologies on that page along with name-allowlist...I just couldn't get anything I was super happy with. Because this repo is for a course/video series,  I wanted Zephyr, Zephyr-SDK, and third-party modules to live outside of the workspace so I could focus on constructing multiple, small, out-of-tree demo applications. The closest thing is the T3 topology, but I super struggled with getting the top-level west.yml to do what I wanted. I might return to it at some point, but for now, the modified west.yml is working (well enough...even if it's not an ideal use of west).
